### PR TITLE
Update to Guzzle 7

### PR DESCRIPTION
**Pull request by bumbummen99**
As the title says. This will require https://github.com/guzzle/command/pull/40

- Remove deprecated function Uri::resolve
- Fix tests
- Update for Guzzle 7

### CODE REVIEW

**Comment by bumbummen99** [comment]
Tests working with `"skyraptor/command": "dev-master"`

**Comment by Konafets** [comment]
As `guzzle/guzzle` requires PHP 7.2, I would suggest to drop all PHP versions <7.2 and add 7.2, 7.3 and 7.4. What do you think?

**Comment by bumbummen99** [comment]
@Konafets Personally i think support for [EOL](https://www.php.net/supported-versions.php) versions should not be priority anyways so +

**Comment by elijahchancey** [comment]
@bumbummen99 Do you or anyone else know how to fix the tests? Looks like there's a PHP version issue and a test Setup Issue.

**Comment by bumbummen99** [comment]
@elijahchancey It just requires guzzle/command to also be patched, see the mentioned PR in the first post. The tests should work with it.

**Comment by Konafets** [comment]
Thanks for the work and progress on this PR. I am in the middle of renovation my new home but will take care of this and release a new version within the next days.

**Comment by arthurkirkosa** [comment]
Any timeline on this merge?

**Comment by bumbummen99** [comment]
> Any timeline on this merge?

https://github.com/guzzle/guzzle-services/pull/174#issuecomment-700279604

**Comment by digitv** [comment]
I hope for soon merge...because of Laravel 8 as well :man_shrugging:.

**Comment by elijahchancey** [comment]
@Konafets please merge when you can! thanks

**Comment by Konafets** [comment]
Thanks @bumbummen99. I merged a modified version of this PR in 187b530b4ceaabf47dd3a42dbccfce2b979c27f7.

**Comment by arthurkirkosa** [comment]
Do you need to manually trigger packagist to pick up the new tag?

**Pull request closed without merging**
