### PR TITLE
Updated exception message for better debugging

### PR DESCRIPTION
**Pull request by stovak**
It's difficult to debug a fat fingered 'loation' in the config

### CODE REVIEW

**Comment by jeremeamia** [comment]
I realize this was opened a long time ago, but could you possibly explain the difference between what is currently there and what you are proposing?

**Comment by jeremeamia** [comment]
@stovak is it related to #99? /cc @james2doyle

**Comment by james2doyle** [comment]
Yeah my patch is the same

**Comment by jeremeamia** [comment]
Cool. Thanks.

**Pull request merged**
