### PR TITLE
Make Guzzle Services compatible with Guzzle6

### PR DESCRIPTION
**Pull request by Konafets**
The PR makes Guzzle Services compatible with Guzzle6 according to the UnitTests and some testing with own APIs.

I try to stick as close as possible to the old behaviour and kept the options `validate` and `process` which working as before (as I expect).  Both options are enabled by default.

I will do more testing with real API (especially XML response location) at the beginning of next week.

### CODE REVIEW

**Comment by guiyomh** [comment]
:+1:

**Comment by jeremeamia** [comment]
Nice work on this. I don't have time to do an in-depth review, but it looks like this is headed in a good direction. Hopefully my earlier work on this and guzzlehttp/command were helpful.

**Comment by Jaesin** [comment]
I'm wondering since it will be a new major version if we should change `new Description(['baseUrl' => 'https://example.com/']);` to `new Description(['base_uri' => 'https://example.com/']);` to be more consistent with guzzle.

**Comment by Jaesin** [comment]
I am continuing to test this and I'm not seeing any major issues: 

https://travis-ci.org/Jaesin/foo-php-rest-client

**Comment by Konafets** [comment]
@Jaesin Regarding `baseUrl`, I had the same thought but after looking into the code I came to the conclusion that this breaks the consistency of the description keys which are all lowerCamelCase. Best idea I came up with is to rename the key to `baseUri` as well renaming the method `getBaseUrl`. What do you think?

**Comment by Jaesin** [comment]
@Konafets Thanks for the response. I see the dilemma. In my opinion it doesn't matter much in that case. It seems unlikely that the URI would not be a URL.

**Comment by azine** [comment]
Thanx for your work guys. Can't wait to see this merged so https://github.com/rdohms/meetup-api-client/issues/25 can be resolved. :-)

**Comment by z38** [comment]
Thank you for your work! I just tested it too and only found 2 minor issues:
* In `GuzzleHttp\Command\Guzzle\Parameter` is a undeclared dependency on `webmozart/dev`. I think it should be either declared or [replaced](https://github.com/z38/guzzle-services/commit/f72fc90cab651b03a3529b73537fd78e4a51dcd6).
* Default command options are not honored. The code was probably lost during refactoring. There is [a simple fix](https://github.com/z38/guzzle-services/commit/e1ef12467eff871b6ab91cc13bccaaf94ef6953a) however.

**Pull request merged**
